main: "me.mrletsplay.webinterfaceapi.bukkit.WebinterfacePlugin"
name: "WebinterfaceAPI"
version: "${project.version}"
api-version: "1.13"
author: "MrLetsplay2003"
softdepend: ["MrCore_BukkitImpl"]
commands:
  webinterfaceapi:
    aliases: ["wiapi"]